- .github/workflows/oidc_core.yaml
- packages/oidc_core/analysis_options.yaml
- packages/oidc_core/lib/src/endpoints/token/token.dart
- packages/oidc_core/test/model_test.dart
- packages/oidc_desktop/lib/src/oidc_desktop.dart
- packages/oidc_platform_interface/lib/src/platform.dart
- Fixes `OidcToken` duration calculations
- Address lints
> fix: token date calculations

- .github/workflows/dart_package.yaml
- .github/workflows/flutter_package.yaml
- .github/workflows/oidc.yaml
- .github/workflows/oidc_core.yaml
- .github/workflows/oidc_loopback_listener.yaml
- packages/oidc/example/ios/Flutter/AppFrameworkInfo.plist
- packages/oidc/example/ios/Podfile
- packages/oidc/example/lib/app_state.dart
- packages/oidc/example/lib/pages/secret_page.dart
- packages/oidc/lib/src/managers/user_manager.dart
- packages/oidc_core/lib/src/endpoints/_exports.dart
- packages/oidc_core/lib/src/endpoints/facade.dart
- packages/oidc_core/lib/src/endpoints/token/token.dart
- packages/oidc_core/lib/src/endpoints/userinfo/_exports.dart
- packages/oidc_core/lib/src/managers/token_events.dart
- packages/oidc_core/lib/src/models/state/state.dart
- packages/oidc_core/lib/src/models/user.dart
- packages/oidc_core/pubspec.yaml
- packages/oidc_core/test/event_manager_test.dart
- packages/oidc_core/test/model_test.dart
**feat**: use package:clock for better testing
**chore**: add OidcTokenEventsManager tests
> chore: improve test coverage

- .github/workflows/oidc_android.yaml
- .github/workflows/oidc_core.yaml
- .github/workflows/oidc_default_store.yaml
- .github/workflows/oidc_desktop.yaml
- .github/workflows/oidc_flutter_appauth.yaml
- .github/workflows/oidc_ios.yaml
- .github/workflows/oidc_linux.yaml
- .github/workflows/oidc_loopback_listener.yaml
- .github/workflows/oidc_macos.yaml
- .github/workflows/oidc_platform_interface.yaml
- .github/workflows/oidc_web.yaml
- .github/workflows/oidc_windows.yaml
each workflow should run based on where the changes happened.
> ci: workflows should run on specific directory change.

- docs/oidc-getting-started.md
- docs/oidc_core.md
- mkdocs.yml
- packages/oidc/README.md
- packages/oidc_core/example/oidc_core_example.dart
- packages/oidc_core/lib/src/models/user.dart
- packages/oidc_core/pubspec.yaml
> docs: Improve readme

- docs/oidc-getting-started.md
- packages/oidc/example/ios/Runner.xcodeproj/project.pbxproj
- packages/oidc/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/oidc/example/ios/Runner/Info.plist
- packages/oidc/example/lib/app_state.dart
- packages/oidc/example/macos/Runner.xcodeproj/project.pbxproj
- packages/oidc/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
- packages/oidc/example/macos/Runner/DebugProfile.entitlements
- packages/oidc/example/macos/Runner/Info.plist
- packages/oidc/example/macos/Runner/Release.entitlements
fixes macos and ios example config
> fix: mac os and ios

- packages/oidc/example/lib/app_state.dart
- packages/oidc/lib/src/managers/user_manager.dart
- packages/oidc/lib/src/models/user_manager_settings.dart
- packages/oidc/pubspec.yaml
- packages/oidc_core/lib/src/constants.dart
- packages/oidc_core/lib/src/endpoints/facade.dart
- packages/oidc_core/lib/src/endpoints/userinfo/_exports.dart
- packages/oidc_core/lib/src/endpoints/userinfo/request.dart
- packages/oidc_core/lib/src/endpoints/userinfo/response.dart
- packages/oidc_core/lib/src/endpoints/userinfo/response.g.dart
- packages/oidc_core/lib/src/endpoints/userinfo/source.dart
- packages/oidc_core/lib/src/endpoints/userinfo/source.g.dart
- packages/oidc_core/lib/src/models/user.dart
- packages/oidc_core/pubspec.yaml
> feat: Add OpenId Connect Certification client config to example

- CHANGELOG.md
- docs/oidc-usage.md
- packages/oidc/CHANGELOG.md
- packages/oidc/example/integration_test/app_test.dart
- packages/oidc/example/lib/app_state.dart
- packages/oidc/example/lib/pages/secret_page.dart
- packages/oidc/lib/src/managers/user_manager.dart
- packages/oidc/pubspec.yaml
> feat: Support manually refreshing tokens

- .github/dependabot.yaml
- .github/workflows/ci.yaml
- .vscode/launch.json
- docs/oidc-usage.md
- packages/oidc/lib/src/managers/user_manager.dart
- packages/oidc/lib/src/models/_exports.dart
- packages/oidc/lib/src/models/event.dart
This PR introduces events, which are raised before user logout for now.
> feat: Add events

- packages/oidc/test/mock_client.dart
- packages/oidc_core/lib/src/endpoints/facade.dart
> fix: improve OidcEndpoints error handling

- packages/oidc_core/lib/src/managers/user_manager_base.dart
fixes https://github.com/Bdaya-Dev/oidc/issues/72
> fix: logout options not being used

- packages/oidc/example/lib/pages/auth.dart
- packages/oidc_core/lib/src/managers/user_manager_base.dart
- packages/oidc_core/lib/src/models/settings/user_manager_settings.dart
- packages/oidc_core/lib/src/models/user.dart
- fixes #62
- Introduce `getIdToken` in user manager settings, to allow using a JWT access_token as an id_token
> feat: add getIdToken to OidcUserManagerSettings

- docs/oidc-usage.md
- docs/oidc_web_core.md
- packages/oidc/example/lib/app_state.dart
- packages/oidc/example/lib/pages/auth.dart
- packages/oidc/example/lib/pages/secret_page.dart
- packages/oidc_core/lib/src/constants.dart
- packages/oidc_core/lib/src/managers/_exports.dart
- packages/oidc_core/lib/src/managers/jwks_store_loader.dart
- packages/oidc_core/lib/src/managers/user_manager_base.dart
- packages/oidc_core/lib/src/models/settings/user_manager_settings.dart
- packages/oidc_core/lib/src/models/user.dart
- packages/oidc_core/lib/src/state_store.dart
- introduce `supportOfflineAuth` in user manager settings.
- fixes #69 
- supersedes #71
> feat: support offline auth

- packages/oidc/lib/src/facade.dart
- packages/oidc/lib/src/managers/user_manager.dart
- packages/oidc_android/test/oidc_android_test.dart
- packages/oidc_core/example/cli_user_manager.dart
- packages/oidc_core/lib/src/managers/user_manager_base.dart
- packages/oidc_desktop/lib/src/oidc_desktop.dart
- packages/oidc_flutter_appauth/lib/src/oidc_flutter_appauth.dart
- packages/oidc_flutter_appauth/test/oidc_flutter_appauth_test.dart
- packages/oidc_ios/test/oidc_ios_test.dart
- packages/oidc_macos/test/oidc_macos_test.dart
- packages/oidc_platform_interface/lib/src/platform.dart
- packages/oidc_web/lib/oidc_web.dart
- packages/oidc_web_core/lib/src/oidc_web_core.dart
- packages/oidc_web_core/lib/src/user_manager_web.dart
- BREAKING CHANGE: added `prepareForRedirectFlow` to OidcPlatform
- fixes #31
- supersedes #32
> fix!: Browsers blocking popups and new tabs due to delay between button press and opening popup

- .github/workflows/tests.yaml
> ci: bump actions/checkout@v4

- packages/oidc_core/lib/src/endpoints/facade.dart
Adds minimal changes to implement Nonce Hashing as suggested in spec: https://openid.net/specs/openid-connect-core-1_0.html#NonceNotes
thanks [MarkLinovy](https://github.com/MarkLinovy) for the actual work.
As i urgently need a distinction between raw and hashed nonce in my project, i have an alternative non-breaking solution on offer here. I would be happy if we could choose one of the two solutions for a merge.
> feat: minimal implement nonce hashing 

- .github/workflows/docs.yaml
> chore(deps): use actions/upload-pages-artifact@v3

- .github/workflows/docs.yaml
> try fix deploy docs

- packages/oidc_default_store/lib/src/oidc_default_store.dart
> fix: oidc_default_store init() loads the shared preferences again

- docs/oidc-usage.md
- packages/oidc_linux/lib/oidc_linux.dart
> docs!: Document multi-manager support

- .vscode/mcp.json
- docs/oidc-usage.md
- packages/oidc_core/lib/src/constants.dart
- packages/oidc_core/lib/src/endpoints/_exports.dart
- packages/oidc_core/lib/src/endpoints/facade.dart
- packages/oidc_core/lib/src/endpoints/revocation/_exports.dart
- packages/oidc_core/lib/src/endpoints/revocation/request.dart
- packages/oidc_core/lib/src/endpoints/revocation/request.g.dart
- packages/oidc_core/lib/src/endpoints/revocation/response.dart
- packages/oidc_core/lib/src/endpoints/revocation/response.g.dart
- packages/oidc_core/lib/src/hooks/oidc_user_manager_hooks.dart
- packages/oidc_core/lib/src/managers/user_manager_base.dart
- packages/oidc_core/lib/src/models/settings/user_manager_settings.dart
- packages/oidc_core/test/endpoints/device_authorization_test.dart
> feat: token revocation

- .github/workflows/tests.yaml
- README.md
- docs/index.md
- packages/oidc/README.md
- packages/oidc/example/integration_test/app_test.dart
- packages/oidc/example/integration_test/conformance/api.dart
- packages/oidc/example/pubspec.yaml
- packages/oidc_android/README.md
- packages/oidc_core/README.md
- packages/oidc_default_store/README.md
- packages/oidc_desktop/README.md
- packages/oidc_flutter_appauth/README.md
- packages/oidc_ios/README.md
- packages/oidc_linux/README.md
- packages/oidc_loopback_listener/README.md
- packages/oidc_macos/README.md
- packages/oidc_platform_interface/README.md
- packages/oidc_web/README.md
- packages/oidc_web_core/README.md
- packages/oidc_windows/README.md
> feat: enhance logging in OIDC conformance tests
